Controllers/InvitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MeteorStrike.Data;
using MeteorStrike.Models;
using MeteorStrike.Extentions;
using MeteorStrike.Services.Interfaces;
using MeteorStrike.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.DataProtection;
using DailyRoarBlog.Data;
using Microsoft.AspNetCore.Authorization;
using MailKit;
using Microsoft.AspNetCore.Identity.UI.Services;

namespace MeteorStrike.Controllers
{
    [Authorize(Roles = "Admin")]

    public class InvitesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBTProjectService _btProjectService;
        private readonly IBTCompanyService _btCompanyService;
        private readonly IEmailSender _btMailService;
        private readonly IBTInviteService _btInviteService;
        private readonly UserManager<BTUser> _userManager;
        private readonly IDataProtector _protector;
        private readonly IConfiguration _configuration;

        public InvitesController(ApplicationDbContext context,
                                 IBTProjectService bTProjectService,
                                 IBTCompanyService btCompanyService,
                                 IEmailSender btEmailService,
                                 IBTInviteService bTInviteService,
                                 UserManager<BTUser> userManager,
                                 IDataProtectionProvider dataProtectionProvider,
                                 IConfiguration configuration)
        {
            _context = context;
            _btProjectService = bTProjectService;
            _btCompanyService = btCompanyService;
            _btMailService = btEmailService;
            _btInviteService = bTInviteService;
            _userManager = userManager;
            _configuration = configuration;
            _protector = dataProtectionProvider.CreateProtector(configuration.GetValue<string>("ProtectKey")! ?? Environment.GetEnvironmentVariable("ProtectKey")!);
        }

        // GET: Invites
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Invites.Include(i => i.Company).Include(i => i.Invitee).Include(i => i.Invitor).Include(i => i.Project);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Invites/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Invites == null)
            {
                return NotFound();
            }

            var invite = await _context.Invites
                .Include(i => i.Company)
                .Include(i => i.Invitee)
                .Include(i => i.Invitor)
                .Include(i => i.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (invite == null)
            {
                return NotFound();
            }

            return View(invite);
        }
        [Authorize(Roles = "Admin")]
        // GET: Invites/Create
        public async Task<IActionResult> Create()
        {
            int? companyId = User.Identity!.GetCompanyId();

            ViewData["ProjectId"] = new SelectList(await _btProjectService.GetProjectsAsync(companyId.Value), "Id", "Name");

            return View();
        }
        [Authorize(Roles = "Admin")]
        // POST: Invites/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProjectId,InviteeEmail,InviteeFirstName,InviteeLastName,Message")] Invite invite)
        {
            int companyId = User.Identity!.GetCompanyId();

            ModelState.Remove("InvitorId");

            if (ModelState.IsValid)
            {
                try
                {
                    Guid guid = Guid.NewGuid();

                    string? token = _protector.Protect(guid.ToString());
                    string? email = _protector.Protect(invite.InviteeEmail!);
                    string? company = _protector.Protect(companyId.ToString());

                    string? callbackUrl = Url.Action("ProcessInvite", "Invites", new { token, email, company }, protocol: Request.Scheme);

                    string body = $@"{invite.Message} <br />
                       Please join my Company. <br />
                       Click the following link to join our team. <br />
                       <a href=""{callbackUrl}"">COLLABORATE</a>";

                    string? destination = invite.InviteeEmail;

                    Company btCompany = await _btCompanyService.GetCompanyInfoAsync(companyId);

                    string? subject = $"AstraTracker : {btCompany.Name} Invite";

                    await _btMailService.SendEmailAsync(destination!, subject, body);

                    // Save Invite to Database
                    invite.CompanyToken = guid;
                    invite.CompanyId = companyId;
                    invite.InviteDate = DataUtility.GetPostGresDate(DateTime.Now);
                    invite.InvitorId = _userManager.GetUserId(User);
                    invite.IsValid= true;

                    await _btInviteService.AddNewInviteAsync(invite);

                    return RedirectToAction(nameof(Index), "Home");

                    //TODO Sweet Alert?
                }
                catch (Exception)
                {

                    throw;
                }

            }

            ViewData["ProjectId"] = new SelectList(await _btProjectService.GetProjectsAsync(companyId), "Id", "Name");
            return View(invite);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> ProcessInvite(string token, string email, string company)
        {
            if (string.IsNullOrEmpty(token) || string.IsNullOrEmpty(email) || string.IsNullOrEmpty(company)) 
            {
                return NotFound();
            }

            Guid? companyToken = Guid.Parse(_protector.Unprotect(token));
            string? inviteeEmail = _protector.Unprotect(email);
            int companyId = int.Parse(_protector.Unprotect(company));

            try
            {
                Invite? invite = await _btInviteService.GetInviteAsync(companyToken, inviteeEmail, companyId);

                if(invite != null)  
                { 
                    return View(invite);
                }

                return NotFound();
            }
            catch (Exception)
            {

                throw;
            }

        }

    }
}

Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MeteorStrike.Data;
using MeteorStrike.Models;
using Microsoft.AspNetCore.Identity;
using DailyRoarBlog.Data;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel.Design;
using MeteorStrike.Services.Interfaces;
using MeteorStrike.Extentions;
using X.PagedList;
using System.Net.Sockets;
using MeteorStrike.Services;
using MeteorStrike.Models.Enums;
using MeteorStrike.Models.ViewModels;
using Org.BouncyCastle.Bcpg;

namespace MeteorStrike.Controllers
{
    [Authorize]

    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BTUser> _userManager;
        private readonly IBTFileService _btFileService;
        private readonly IBTTicketService _btTicketService;
        private readonly IBTRolesService _btRolesService;
        private readonly IBTTicketHistoryService _btTicketHistoryService;
        private readonly IBTProjectService _btProjectService;
        private readonly IBTNotification _btNotification;

        public TicketsController(ApplicationDbContext context,
                                  UserManager<BTUser> userManager,
                                  IBTFileService btFileService,
                                  IBTTicketService btTicketService,
                                  IBTRolesService btRolesService,
                                  IBTTicketHistoryService btTicketHistoryService, 
                                  IBTProjectService btProjectService,
                                  IBTNotification btNotification)
        {
            _context = context;
            _userManager = userManager;
            _btFileService = btFileService;
            _btTicketService = btTicketService;
            _btRolesService = btRolesService;
            _btTicketHistoryService = btTicketHistoryService;
            _btProjectService = btProjectService;
            _btNotification = btNotification;
        }


        //GET: MyTickets
        public async Task<IActionResult> TicketHistory()
        { 
            int companyId = User.Identity!.GetCompanyId();

            IEnumerable<TicketHistory> ticketHistory = await _btTicketHistoryService.GetCompanyTicketHistoriesAsync(companyId); 

            return View(ticketHistory);
        }

        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            int companyId = User.Identity!.GetCompanyId();

            IEnumerable<Ticket> tickets = await _btTicketService.GetTicketsAsync(companyId);

            return View(tickets);
        }

        // GET: Tickets
        public async Task<IActionResult> MyTickets()
        {
            string? userId = _userManager.GetUserId(User);

            int? companyId = User.Identity!.GetCompanyId();

            IEnumerable<Ticket> tickets = await _btTicketService.GetUserTicketsAsync(userId, companyId);

            return View(tickets);
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            int companyId = User.Identity!.GetCompanyId();

            if (id == null)
            {
                return NotFound();
            }

            Ticket ticket = await _btTicketService.GetTicketAsync(id, companyId);

            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, ProjectManager")]
        //GET: Assign Ticket Members
        public async Task<IActionResult> AssignTicketMember(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int companyId = User.Identity!.GetCompanyId();

            Ticket ticket = await _btTicketService.GetTicketAsync(id, companyId);

            List<BTUser> developers = await _btRolesService.GetUsersInRoleAsync(nameof(BTRoles.Developer), companyId);

            string? currentDeveloperId = ticket.DeveloperUser?.Id;

            TicketMemberViewModel viewModel = new()
            {
                Ticket = ticket,
                UserList = new SelectList(developers, "Id", "FullName", currentDeveloperId),
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, ProjectManager")]
        //POST: Assign Ticket Members
        public async Task<IActionResult> AssignTicketMember(TicketMemberViewModel viewModel)
        {
            int companyId = User.Identity!.GetCompanyId();

            Ticket ticket = await _btTicketService.GetTicketAsync(viewModel.Ticket?.Id, companyId);

			if (viewModel.DeveloperId != null)
            {
                //Add newly selected member
                ticket.DeveloperUserId = viewModel.DeveloperId;

                await _btTicketService.UpdateTicketAsync(ticket);

                return RedirectToAction(nameof(Details), new { id = viewModel.Ticket!.Id });
            }

            ModelState.AddModelError("SelectedMembers", "No Users selected. Please select some Users.");

            //History
            string? userId = _userManager.GetUserId(User);
			Ticket? newTicket = await _btTicketService.GetTicketAsNoTrackingAsync(ticket.Id, companyId);

			await _btTicketHistoryService.AddHistoryAsync(null, newTicket, userId);

			// Notification
			BTUser? btUser = await _userManager.GetUserAsync(User);

			Notification? notification = new()
			{
				TicketId = ticket.Id,
				Title = "Developer Assigned",
				Message = $"Ticket: {ticket.Title} was assigned by by {btUser?.FullName}.",
				Created = DataUtility.GetPostGresDate(DateTime.UtcNow),
				SenderId = userId,
				RecipientId =ticket.DeveloperUserId,
				NotificationTypeId = (await _context.NotificationTypes.FirstOrDefaultAsync(n => n.Name == nameof(BTNotificationTypes.Ticket)))!.Id
			};
			    
            await _btNotification.AdminNotificationAsync(notification, companyId);
			    
            await _btNotification.SendAdminEmailNotificationAsync(notification, "New Ticket Added; No Project Manager Found", companyId);
                


			return View(viewModel);

        }


        // GET: Tickets/Create
        public async Task<IActionResult> Create()
        {
            string? userId = _userManager.GetUserId(User);

            int companyId = User.Identity!.GetCompanyId();

            BTUser btUser = await _userManager.GetUserAsync(User);

            IEnumerable<Project> projects = await _btProjectService.GetCompanyProjectsAsync(companyId);

            IEnumerable<Project> userProjects = projects.Where(p => p.Members.Any(m => m.Id == userId));

            if (User.IsInRole("Admin"))
            {
                ViewData["ProjectId"] = new SelectList(projects, "Id", "Name");
            } 
            else
            {
                ViewData["ProjectId"] = new SelectList(userProjects, "Id", "Name");
            }


            ViewData["TicketPriorityId"] = new SelectList(await _btTicketService.GetTicketPriorities(), "Id", "Name");
            ViewData["TicketTypeId"] = new SelectList(await _btTicketService.GetTicketTypes(), "Id", "Name");

            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Created,Updated,Archived,ArchivedByProject,ProjectId,TicketTypeId,TicketStatusId,TicketPriorityId,DeveloperUserId,SubmitterUserId")] Ticket ticket)
        {
            ModelState.Remove("SubmitterUserId");

            int companyId = User.Identity!.GetCompanyId();

            if (ModelState.IsValid)
            {

                BTUser? btUser = await _userManager.GetUserAsync(User);

                ticket.SubmitterUserId = btUser!.Id;

                ticket.Created = DataUtility.GetPostGresDate(DateTime.UtcNow);

                ticket.Updated = DataUtility.GetPostGresDate(DateTime.UtcNow);

                ticket.TicketStatusId = 1;

                await _btTicketService.AddTicketAsync(ticket);

                string? userId = _userManager.GetUserId(User);

                // History
                Ticket? newTicket = await _btTicketService.GetTicketAsNoTrackingAsync(ticket.Id, companyId);

                await _btTicketHistoryService.AddHistoryAsync(null, newTicket, userId);


                // Notification
                BTUser? projectManager = await _btProjectService.GetProjectManagerAsync(ticket.ProjectId);

                Notification? notification = new()
                {
                    ProjectId = ticket.ProjectId,
                    TicketId = ticket.Id,
                    Title = "New Ticket Added",
                    Message = $"New Ticket: {ticket.Title} was created by {btUser?.FullName}.",
                    Created= DataUtility.GetPostGresDate(DateTime.UtcNow),
                    SenderId = userId,
                    RecipientId = projectManager?.Id,
                    NotificationTypeId = (await _context.NotificationTypes.FirstOrDefaultAsync(n=>n.Name == nameof(BTNotificationTypes.Ticket)))!.Id
                };

                if (projectManager != null )
                {
                    await _btNotification.AddNotificationAsync(notification);
                    await _btNotification.SendEmailNotificationAsync(notification, "New Ticket Added");
                }
                else
                {
                    await _btNotification.AdminNotificationAsync(notification, companyId);

Views/Invites/Create.cshtml
@model MeteorStrike.Models.Invite

@{
    ViewData["Title"] = "Create";
}

<!-- ============================================================== -->
 <!-- Bread crumb and right sidebar toggle -->
 <!-- ============================================================== -->
 <div class="page-breadcrumb border-bottom">
     <div class="row">
         <div class="col-lg-3 col-md-4 col-xs-12 justify-content-start d-flex align-items-center">
             <h5 class="font-weight-medium text-uppercase mb-0">Create Invite</h5>
         </div>
         <div class="col-lg-9 col-md-8 col-xs-12 d-flex justify-content-start justify-content-md-end align-self-center">
             <nav aria-label="breadcrumb" class="mt-2">
                 <ol class="breadcrumb mb-0 p-0">
                     <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                     <li class="breadcrumb-item active"><a asp-controller="Home" asp-action="Index">Dashboard</a></li>
                     <li class="breadcrumb-item active" aria-current="page"><b><a asp-controller="Invites" asp-action="Create">Create Invite</a></b></li>
                 </ol>
             </nav>
             <a asp-controller="Tickets" asp-action="Create" class="btn btn-danger text-white ms-3 d-none d-md-block">Create Ticket</a>
         </div>
     </div>
 </div>
 <!-- ============================================================== -->
 <!-- End Bread crumb and right sidebar toggle -->
 <!-- ============================================================== -->
<div class="container p-3">
<div class="row justify-content-center">
<div class="col-lg-6 col-md-12">
    <div class="card custom-card">
        <div class="card-body">
            <div>
                <h4 class="main-content-label mb-1">Create a new Company Invite</h4>
                <hr />
            </div>
            <form asp-action="Create">
                 <div class="row row-xs align-items-center mg-b-20">
                    <div class="col-md-4 mt-2">
                        <label class="mg-b-0">Firstname</label>
                    </div>
                    <div class="col-md-8 mg-t-5 mg-md-t-0 mt-2">
                        <input type="text" asp-for="InviteeFirstName" class="form-control" placeholder="Enter first name">
                    </div>
                    <div class="col-md-4 mt-2">
                        <label class="mg-b-0 ">Lastname</label>
                    </div>
                    <div class="col-md-8 mg-t-5 mg-md-t-0 mt-2">
                        <input type="text" asp-for="InviteeLastName" class="form-control" placeholder="Enter last name">
                    </div>
                 </div>
                <div class="row row-xs align-items-center mg-b-20">
                    <div class="col-md-4 mt-2">
                        <label class="mg-b-0">Email</label>
                    </div>
                    <div class="col-md-8 mg-t-5 mg-md-t-0 mt-2">
                        <input type="email" asp-for="InviteeEmail" class="form-control" placeholder="Enter email">
                    </div>
                </div>
                <div class="row row-xs align-items-center mg-b-20">
                    <div class="col-md-4 mt-2">
                        <label class="mg-b-0">Select Project</label>
                    </div>
                    <div class="col-md-8 mg-t-5 mg-md-t-0 mt-2">
                        <select class="form-control" asp-for="ProjectId" asp-items="@ViewBag.ProjectId">
                            <option value="">Select Project</option>
                        </select>
                    </div>
                </div>
                <div class="row row-xs align-items-center mg-b-20">
                    <div class="col-md-4 mt-2">
                        <label class="mg-b-0">Message</label>
                    </div>
                    <div class="col-md-8 mg-t-5 mg-md-t-0 mt-2">
                        <textarea asp-for="Message" multiple="multiple" class="form-control"></textarea>
                    </div>
                </div>
                <div class="form-group row justify-content-end mb-0">
                    <div class="col-md-8 pl-md-2 mt-2 text-end">
                        <input type="submit" class="btn ripple btn-primary pd-x-30 mg-r-5 mt-2" value="Send Invite" />
                        <button class="btn ripple btn-secondary pd-x-30 mt-2">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Invites/Delete.cshtml
@model MeteorStrike.Models.Invite

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invite</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JoinDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JoinDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyToken)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyToken)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteeEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteeEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteeFirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteeFirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteeLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteeLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsValid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsValid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invitor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invitor.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invitee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invitee.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Invites/Details.cshtml
@model MeteorStrike.Models.Invite

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Invite</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JoinDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JoinDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyToken)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyToken)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteeEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteeEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteeFirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteeFirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InviteeLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InviteeLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsValid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsValid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invitor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invitor.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invitee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invitee.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Invites/Edit.cshtml
@model MeteorStrike.Models.Invite

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Invite</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="InviteDate" class="control-label"></label>
                <input asp-for="InviteDate" class="form-control" />
                <span asp-validation-for="InviteDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JoinDate" class="control-label"></label>
                <input asp-for="JoinDate" class="form-control" />
                <span asp-validation-for="JoinDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyToken" class="control-label"></label>
                <input asp-for="CompanyToken" class="form-control" />
                <span asp-validation-for="CompanyToken" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InviteeEmail" class="control-label"></label>
                <input asp-for="InviteeEmail" class="form-control" />
                <span asp-validation-for="InviteeEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InviteeFirstName" class="control-label"></label>
                <input asp-for="InviteeFirstName" class="form-control" />
                <span asp-validation-for="InviteeFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InviteeLastName" class="control-label"></label>
                <input asp-for="InviteeLastName" class="form-control" />
                <span asp-validation-for="InviteeLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsValid" /> @Html.DisplayNameFor(model => model.IsValid)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CompanyId" class="control-label"></label>
                <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.CompanyId"></select>
                <span asp-validation-for="CompanyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <select asp-for="ProjectId" class="form-control" asp-items="ViewBag.ProjectId"></select>
                <span asp-validation-for="ProjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InvitorId" class="control-label"></label>
                <select asp-for="InvitorId" class="form-control" asp-items="ViewBag.InvitorId"></select>
                <span asp-validation-for="InvitorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InviteeId" class="control-label"></label>
                <select asp-for="InviteeId" class="form-control" asp-items="ViewBag.InviteeId"></select>
                <span asp-validation-for="InviteeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}